site_name: jkphl/micrometa
site_description: A meta parser for extracting micro information out of web documents, currently supporting Microformats 1+2, HTML Microdata, RDFa Lite 1.1 and JSON-LD
site_author: Joschi Kuphal
repo_url: https://github.com/jkphl/micrometa
docs_dir: doc
pages:
- Home: 'index.md'
- To-Do: 'todo.md'
